### ISSUE TITLE
Double deleting confirmation with 2 menu editors on page

### ISSUE THREAD

**Issue by PeterTillema** [davicotico/jQuery-Menu-Editor#20]
When you have a page with 2 menu editors, using the same buttons and whatever, an event is attached twice to the same element (line 1117), which causes a popup message to appear twice. 

Solution: remove the click event listener before setting it.

**Comment by davicotico** [comment]
Hi @PeterTillema, thanks for reporting that issue. I'll check it out and fix it.

**Comment by lucaslm** [comment]
Hello guys.

Wouldn't it be better to limit the event attachment to just the buttons pertaining to the editor being created? No need to dettach and reattach the same event this way.

I figured two ways to do it, and created the following branches for each:

- https://github.com/davicotico/jQuery-Menu-Editor/pull/23
- https://github.com/davicotico/jQuery-Menu-Editor/pull/24

In think I prefer the first one because the event is attached to the $main element and not the whole document, but I'm guessing the click event is attached to the document for some reason I didn't get.

**Comment by davicotico** [comment]
Hi @lucaslm I appreciate your contribution. 
Yes, the first one #23 is the best way.
I am going to merge it. Thanks.

**Comment by davicotico** [comment]
Version 1.1.1 will be released in the next few hours.

**Comment by lucaslm** [comment]
You might want to check the other stuff I've been working on my forking of this project before releasing it.

**Comment by davicotico** [comment]
@lucaslm, I really appreciate your contribution to this project. I've reviewed your other pull requests, however some of them are major changes (require a major version), so there are no plans to include them in this 1.x version. On the other hand, those pull requests that are for improvements (no structural changes), could be included progressively.
